---
coverage_criteria:
  process_abort: true
  timeout: true
includes:
- lib
integration:
  name: minitest
jobs: 10
matcher:
  subjects:
  - NBA*
mutation:
  operators: full
  timeout: 10.0
requires:
- nba
usage: opensource
