require:
 - standard

plugins:
 - rubocop-minitest
 - rubocop-performance
 - rubocop-rake
 - standard-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/LineLength:
  Max: 140

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/ModuleLength:
  Max: 115

Metrics/BlockLength:
  Max: 28

Minitest/MultipleAssertions:
  Max: 5

Naming/VariableNumber:
  CheckSymbols: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/OpenStructUse:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

# Using yield instead of &block forwarding works better with both Steep (type narrowing)
# and Mutant (yield without block raises LocalJumpError, making mutations killable)
Style/ExplicitBlockArgument:
  Enabled: false

# Steep uses #: for inline type annotations
Layout/LeadingCommentSpace:
  AllowSteepAnnotation: true

# Draft endpoint modules have attribute mapping methods that are necessarily long
# These methods map API response keys to model attributes and splitting them
# would reduce clarity without improving maintainability
Metrics/MethodLength:
  Exclude:
    - lib/nba/draft_board.rb
    - lib/nba/draft_combine_drill_results.rb
    - lib/nba/draft_combine_non_stationary_shooting.rb
    - lib/nba/draft_combine_player_anthro.rb
    - lib/nba/draft_combine_spot_shooting.rb
    - lib/nba/draft_combine_stats.rb

Metrics/AbcSize:
  Exclude:
    - lib/nba/draft_board.rb

Metrics/ModuleLength:
  Exclude:
    - lib/nba/draft_combine_non_stationary_shooting.rb
    - lib/nba/draft_combine_spot_shooting.rb
    - lib/nba/box_score_advanced_v3.rb
    - lib/nba/box_score_defensive_v2.rb
    - lib/nba/box_score_matchups_v3.rb
    - lib/nba/team_info_common.rb
    - lib/nba/team_player_on_off_details.rb
    - lib/nba/team_player_on_off_summary.rb
