require_relative "../test_helper"

module NBA
  module DraftCombineNonStationaryShootingMissingKeysHelper
    FULL_HEADERS = %w[
      TEMP_PLAYER_ID PLAYER_ID PLAYER_NAME FIRST_NAME LAST_NAME POSITION
      OFF_DRIBBLE_FIFTEEN_BREAK_LEFT_MADE OFF_DRIBBLE_FIFTEEN_BREAK_LEFT_ATTEMPT
      OFF_DRIBBLE_FIFTEEN_BREAK_LEFT_PCT OFF_DRIBBLE_FIFTEEN_TOP_KEY_MADE
      OFF_DRIBBLE_FIFTEEN_TOP_KEY_ATTEMPT OFF_DRIBBLE_FIFTEEN_TOP_KEY_PCT
      OFF_DRIBBLE_FIFTEEN_BREAK_RIGHT_MADE OFF_DRIBBLE_FIFTEEN_BREAK_RIGHT_ATTEMPT
      OFF_DRIBBLE_FIFTEEN_BREAK_RIGHT_PCT
      ON_MOVE_FIFTEEN_BREAK_LEFT_MADE ON_MOVE_FIFTEEN_BREAK_LEFT_ATTEMPT
      ON_MOVE_FIFTEEN_BREAK_LEFT_PCT ON_MOVE_FIFTEEN_TOP_KEY_MADE
      ON_MOVE_FIFTEEN_TOP_KEY_ATTEMPT ON_MOVE_FIFTEEN_TOP_KEY_PCT
      ON_MOVE_FIFTEEN_BREAK_RIGHT_MADE ON_MOVE_FIFTEEN_BREAK_RIGHT_ATTEMPT
      ON_MOVE_FIFTEEN_BREAK_RIGHT_PCT
      OFF_DRIBBLE_COLLEGE_BREAK_LEFT_MADE OFF_DRIBBLE_COLLEGE_BREAK_LEFT_ATTEMPT
      OFF_DRIBBLE_COLLEGE_BREAK_LEFT_PCT OFF_DRIBBLE_COLLEGE_TOP_KEY_MADE
      OFF_DRIBBLE_COLLEGE_TOP_KEY_ATTEMPT OFF_DRIBBLE_COLLEGE_TOP_KEY_PCT
      OFF_DRIBBLE_COLLEGE_BREAK_RIGHT_MADE OFF_DRIBBLE_COLLEGE_BREAK_RIGHT_ATTEMPT
      OFF_DRIBBLE_COLLEGE_BREAK_RIGHT_PCT
      ON_MOVE_COLLEGE_BREAK_LEFT_MADE ON_MOVE_COLLEGE_BREAK_LEFT_ATTEMPT
      ON_MOVE_COLLEGE_BREAK_LEFT_PCT ON_MOVE_COLLEGE_TOP_KEY_MADE
      ON_MOVE_COLLEGE_TOP_KEY_ATTEMPT ON_MOVE_COLLEGE_TOP_KEY_PCT
      ON_MOVE_COLLEGE_BREAK_RIGHT_MADE ON_MOVE_COLLEGE_BREAK_RIGHT_ATTEMPT
      ON_MOVE_COLLEGE_BREAK_RIGHT_PCT
    ].freeze

    FULL_ROW = [
      1, 1_630_162, "Victor Wembanyama", "Victor", "Wembanyama", "C",
      3, 5, 0.6, 4, 5, 0.8, 3, 5, 0.6,
      2, 5, 0.4, 3, 5, 0.6, 2, 5, 0.4,
      2, 5, 0.4, 3, 5, 0.6, 2, 5, 0.4,
      1, 5, 0.2, 2, 5, 0.4, 1, 5, 0.2
    ].freeze

    def stub_with_headers_except(key)
      headers = FULL_HEADERS.reject { |h| h.eql?(key) }
      row = headers.map { |h| FULL_ROW[FULL_HEADERS.index(h)] }
      response = {resultSets: [{name: "Results", headers: headers, rowSet: [row]}]}
      stub_request(:get, /draftcombinenonstationaryshooting/).to_return(body: response.to_json)
    end
  end
end
