require_relative "../../test_helper"

module NBA
  module DraftCombineSpotShootingMissingKeysHelper
    FULL_HEADERS = %w[
      PLAYER_ID PLAYER_NAME FIRST_NAME LAST_NAME POSITION
      FIFTEEN_CORNER_LEFT_MADE FIFTEEN_CORNER_LEFT_ATTEMPT FIFTEEN_CORNER_LEFT_PCT
      FIFTEEN_BREAK_LEFT_MADE FIFTEEN_BREAK_LEFT_ATTEMPT FIFTEEN_BREAK_LEFT_PCT
      FIFTEEN_TOP_KEY_MADE FIFTEEN_TOP_KEY_ATTEMPT FIFTEEN_TOP_KEY_PCT
      FIFTEEN_BREAK_RIGHT_MADE FIFTEEN_BREAK_RIGHT_ATTEMPT FIFTEEN_BREAK_RIGHT_PCT
      FIFTEEN_CORNER_RIGHT_MADE FIFTEEN_CORNER_RIGHT_ATTEMPT FIFTEEN_CORNER_RIGHT_PCT
      COLLEGE_CORNER_LEFT_MADE COLLEGE_CORNER_LEFT_ATTEMPT COLLEGE_CORNER_LEFT_PCT
      COLLEGE_BREAK_LEFT_MADE COLLEGE_BREAK_LEFT_ATTEMPT COLLEGE_BREAK_LEFT_PCT
      COLLEGE_TOP_KEY_MADE COLLEGE_TOP_KEY_ATTEMPT COLLEGE_TOP_KEY_PCT
      COLLEGE_BREAK_RIGHT_MADE COLLEGE_BREAK_RIGHT_ATTEMPT COLLEGE_BREAK_RIGHT_PCT
      COLLEGE_CORNER_RIGHT_MADE COLLEGE_CORNER_RIGHT_ATTEMPT COLLEGE_CORNER_RIGHT_PCT
      NBA_CORNER_LEFT_MADE NBA_CORNER_LEFT_ATTEMPT NBA_CORNER_LEFT_PCT
      NBA_BREAK_LEFT_MADE NBA_BREAK_LEFT_ATTEMPT NBA_BREAK_LEFT_PCT
      NBA_TOP_KEY_MADE NBA_TOP_KEY_ATTEMPT NBA_TOP_KEY_PCT
      NBA_BREAK_RIGHT_MADE NBA_BREAK_RIGHT_ATTEMPT NBA_BREAK_RIGHT_PCT
      NBA_CORNER_RIGHT_MADE NBA_CORNER_RIGHT_ATTEMPT NBA_CORNER_RIGHT_PCT
    ].freeze

    FULL_ROW = [
      1_630_162, "Victor Wembanyama", "Victor", "Wembanyama", "C",
      3, 5, 0.6, 4, 5, 0.8, 3, 5, 0.6, 4, 5, 0.8, 3, 5, 0.6,
      4, 5, 0.8, 3, 5, 0.6, 4, 5, 0.8, 3, 5, 0.6, 4, 5, 0.8,
      2, 5, 0.4, 3, 5, 0.6, 4, 5, 0.8, 3, 5, 0.6, 2, 5, 0.4
    ].freeze

    def stub_with_headers_except(key)
      headers = FULL_HEADERS.reject { |h| h.eql?(key) }
      row = headers.map { |h| FULL_ROW[FULL_HEADERS.index(h)] }
      response = {resultSets: [{name: "Results", headers: headers, rowSet: [row]}]}
      stub_request(:get, /draftcombinespotshooting/).to_return(body: response.to_json)
    end
  end
end
